apiVersion: v1
kind: Service
metadata:
  name: earth-station
  namespace: dtn-lab
  labels:
    node-type: ground-station
    location: earth
spec:
  selector:
    app: dtn
    node: earth-station
  ports:
    - name: dtn
      port: 4556
      targetPort: 4556
    - name: metrics
      port: 8080
      targetPort: 8080
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: earth-station
  namespace: dtn-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dtn
      node: earth-station
  template:
    metadata:
      labels:
        app: dtn
        node: earth-station
        location: "goldstone-dsn"
    spec:
      containers:
      - name: earth-station
        image: space-dtn:latest
        imagePullPolicy: Never
        securityContext:
          privileged: true
          capabilities:
            add:
              - NET_ADMIN
        env:
        - name: DTN_NODE_ID
          value: "earth-station"
        - name: DTN_NODE_TYPE
          value: "earth"
        - name: DTN_PORT
          value: "4556"
        - name: DTN_NEIGHBORS
          value: "satellite:satellite:4556"
        ports:
        - containerPort: 4556
          name: dtn
        - containerPort: 8080
          name: metrics
        volumeMounts:
        - name: storage
          mountPath: /store
        - name: telemetry
          mountPath: /telemetry
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
      volumes:
      - name: storage
        emptyDir: {}
      - name: telemetry
        emptyDir: {}