apiVersion: v1
kind: Service
metadata:
  name: satellite
  namespace: dtn-lab
  labels:
    node-type: satellite
    orbit: leo
spec:
  selector:
    app: dtn
    node: satellite
  ports:
    - name: dtn
      port: 4556
      targetPort: 4556
    - name: metrics
      port: 8080
      targetPort: 8080
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: satellite
  namespace: dtn-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dtn
      node: satellite
  template:
    metadata:
      labels:
        app: dtn
        node: satellite
        location: "leo-orbit-400km"
    spec:
      containers:
      - name: satellite
        image: space-dtn:latest
        imagePullPolicy: Never
        securityContext:
          privileged: true
          capabilities:
            add:
              - NET_ADMIN
        env:
        - name: DTN_NODE_ID
          value: "satellite"
        - name: DTN_NODE_TYPE
          value: "satellite"
        - name: DTN_PORT
          value: "4556"
        - name: DTN_NEIGHBORS
          value: "earth-station:earth-station:4556,lunar-base:lunar-base:4556"
        ports:
        - containerPort: 4556
          name: dtn
        - containerPort: 8080
          name: metrics
        volumeMounts:
        - name: storage
          mountPath: /store
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
      volumes:
      - name: storage
        emptyDir: {}