apiVersion: batch/v1
kind: Job
metadata:
  name: telemetry-burst-test
  namespace: dtn-lab
  labels:
    mission: integration-test
    type: telemetry-burst
spec:
  completions: 1
  parallelism: 1
  backoffLimit: 3
  template:
    metadata:
      labels:
        app: test-job
    spec:
      restartPolicy: Never
      containers:
      - name: test-client
        image: busybox:latest
        command: ["/bin/sh"]
        args:
          - -c
          - |
            echo "[TEST-CLIENT] Integration test for Space DTN network"
            echo "[TEST-CLIENT] Testing telemetry burst transmission"
            echo "[TEST-CLIENT] Route: Earth Station -> LEO Satellite -> Lunar Base"
            echo ""
            
            # Wait for all nodes to be ready
            sleep 10
            
            echo "[TEST-CLIENT] Initiating telemetry burst test..."
            echo "[TEST-CLIENT] Simulating high-priority command sequence"
            echo ""
            
            # Simulate sending telemetry commands
            for i in $(seq 1 10); do
              timestamp=$(date +%s)
              
              # Simulate different types of space telemetry
              case $((i % 4)) in
                0) cmd_type="ORBITAL_ADJUST"
                   data="deltaV=2.3m/s,inclination=28.5°" ;;
                1) cmd_type="SCIENCE_DATA_REQ"
                   data="sensors=magnetometer,spectrometer" ;;
                2) cmd_type="SYSTEM_HEALTH_CHECK"
                   data="subsystems=power,thermal,comms" ;;
                3) cmd_type="LUNAR_BASE_SYNC"
                   data="time_sync,weather_update,supply_status" ;;
              esac
              
              echo "[TEST-CLIENT] Injecting test packet #$i into Earth Station queue"
              echo "  ├─ Type: $cmd_type"
              echo "  ├─ Data: $data"
              echo "  ├─ Timestamp: $timestamp"
              echo "  ├─ Frequency: 2.2 GHz (S-band)"
              echo "  └─ Status: Transmitted ✓"
              echo ""
              
              # Longer interval to simulate realistic space operations
              sleep 3
            done
            
            echo "[TEST-CLIENT] Test sequence complete"
            echo "[TEST-CLIENT] Total test packets injected: 10"
            echo "[TEST-CLIENT] Check Earth Station, Satellite, and Lunar Base logs for flow"
            
            sleep 15
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"